### ISSUE TITLE
Silly idea: Return a VersionNumber instead of AbstractString in api_version

### ISSUE THREAD

**Issue by ghost** [rahulkp220/Zabbix.jl#1]
https://github.com/rahulkp220/Zabbix.jl/blob/519e0fc173352c6bd8f29bec2fce7b5e3eec2c38/src/Zabbix.jl#L71

I'm a bit unclear on how version numbers are formatted by the Zabbix api. But I think if they are semver you can use a VersionNumber instead of a string. https://docs.julialang.org/en/stable/manual/strings/ in the "Version Number Literal" section talks about that. 

I think it's mostly useless, but the main thing that's interesting about returning a VersionNumber is that you can do comparisons like this to specialize if future versions of the API have special edge cases: 

```
if v"0.2" <= VERSION < v"0.3-"
    # do something specific to 0.2 release series
end
```

Which I could imagine would be useful if you need to maintain this long term.

**Comment by rahulkp220** [comment]
`Starting from Zabbix 2.0.4 the version of the API matches the version of Zabbix.`
Hence, the idea wasn't silly, thanks for pointing out to a functionality that Julia had. Merged and updated the code. Will make a release soon!
```julia
julia> Zabbix.api_version(zabbix)
v"3.2.11"

julia> typeof(Zabbix.api_version(zabbix))
VersionNumber
```
